/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TripImport } from './routes/Trip'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TripRoute = TripImport.update({
  id: '/Trip',
  path: '/Trip',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Trip': {
      id: '/Trip'
      path: '/Trip'
      fullPath: '/Trip'
      preLoaderRoute: typeof TripImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Trip': typeof TripRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Trip': typeof TripRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Trip': typeof TripRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Trip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Trip'
  id: '__root__' | '/' | '/Trip'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripRoute: typeof TripRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripRoute: TripRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/Trip"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/Trip": {
      "filePath": "Trip.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
